-- Imports
local TUNING = GLOBAL.TUNING

-- Global Damage Settings
LOW_SANITY_THRESHOLD = 0.375
LOW_HUNGER_THRESHOLD = 0.375

-- Damage to Others
GLOBAL_DAMAGE_TO_OTHERS_MULT = 1
LOW_SANITY_DAMAGE_TO_OTHERS_MULT = 0.75
LOW_HUNGER_DAMAGE_TO_OTHERS_MULT = 0.75

-- Damage done to Players
GLOBAL_DAMAGE_DONE_TO_PLAYERS_MULT = 1
LOW_SANITY_DAMAGE_DONE_TO_PLAYERS_MULT = 1.25
LOW_HUNGER_DAMAGE_DONE_TO_PLAYERS_MULT = 1.25

-- Damage done to Shadow Creatures
DAMAGE_TO_SHADOW_CREATURES_BUFF_THRESHOLD = 0.625
DAMAGE_TO_SHADOW_CREATURES_BUFF_MULT = 2

-- Shadow Creatures Buff/Debuff
SHADOW_CREATURES_SANITY_BUFF_MAX_PERCENT = 0.3
SHADOW_CREATURES_SANITY_BUFF_THRESHOLD = 0.22
SHADOW_CREATURES_SANITY_BUFF_AMOUNT = TUNING.SANITY_LARGE
SHADOW_CREATURES_MAX_HEALTH = 600
SHADOW_CREATURES_CREEPINGFEAR_HEALTH = 450
