-- Nightmare Fuel Chance Reduction
SHADOW_CREATURES_NIGHTMARE_FUEL_CHANCE = 0
RABBIT_NIGHTMARE_FUEL_CHANCE = 0.05

-- Character List Still Dropping Nightmare Fuel
NIGHTMAREFUEL_INCREASE_DROP_CHANCE_BONUS = 0.33
NIGHTMAREFUEL_INCREASE_DROP_RANGE = 20
NIGHTMAREFUEL_INCREASE_DROP_CHARACTERS = 
{
    "waxwell"
}
