-- Discord Command Settings
DISCORD_EVENT_OCCURANCE_CHANCE = 0.5
DISCORD_EVENT_POSITIVE_CHANCE = 0.75
DISCORD_EVENT_POSITIVE_HEALTH_THRESHOLD = 0.375
DISCORD_EVENT_POSITIVE_HUNGER_THRESHOLD = 0.375
DISCORD_EVENT_POSITIVE_SANITY_THRESHOLD = 0.375
DISCORD_EVENT_POSITIVE_FIREPIT_TIME = 30
DISCORD_EVENT_POSITIVE_FREEZING_THRESHOLD = 10
DISCORD_EVENT_POSITIVE_OVERHEATING_THRESHOLD = 60
DISCORD_UNKNOWN_EMOJI = ":grey_question: "
DISCORD_WARNING_EMOJI = ":warning: "
