WORLD_RESET_ATRIUM_PROTECTION_DAYS = 48
WORLD_RESET_MOONALTAR_PROTECTION_DAYS = 12
WORLD_RESET_ATRIUM_DEATH_DAY_COST = 2
WORLD_RESET_ATRIUM_PROTECTION_ITEM = "moonrockcrater"
WORLD_RESET_MOONALTAR_PROTECTION_ITEM = "moonrockcrater"

WORLD_RESET_START_AFTER_DATE = 12
WORLD_RESET_EARTHQUAKE_DURATION = 10
WORLD_RESET_EARTHQUAKE_MINIMUM_COOLDOWN = 15
WORLD_RESET_EARTHQUAKE_BASE_CHANCE = 0.1

WORLD_RESET_ATRIUM_ROLLBACK_DAYS = 3
WORLD_RESET_ATRIUM_ROLLBACK_FILENAME = "madness_rollback"
