-- Imports
local TUNING = GLOBAL.TUNING

-- Very Short
TUNING.SEASON_LENGTH_FRIENDLY_VERYSHORT = 3
TUNING.SEASON_LENGTH_HARSH_VERYSHORT = 7

-- Short
TUNING.SEASON_LENGTH_FRIENDLY_SHORT = 11
TUNING.SEASON_LENGTH_HARSH_SHORT = 13

-- Default
TUNING.SEASON_LENGTH_FRIENDLY_DEFAULT = 17
TUNING.SEASON_LENGTH_HARSH_DEFAULT = 21

-- Long
TUNING.SEASON_LENGTH_FRIENDLY_LONG = 25
TUNING.SEASON_LENGTH_HARSH_LONG = 35

-- Very Long
TUNING.SEASON_LENGTH_FRIENDLY_VERYLONG = 45
TUNING.SEASON_LENGTH_HARSH_VERYLONG = 55
